s-knibbs/dataclasses-jsonschema

README.rst
dataclasses_jsonschema/__init__.py
tests/conftest.py
tests/test_all.py

Generate correct schema for integer & float types
Fixes #7

Add support for tuple types, using JSON schema tuple validation

---

dataclasses_jsonschema/__init__.py
tests/conftest.py
tests/test_all.py

Fix #18: Non string keys are now deserialised correctly from JSON

Fix #19: NewType types are now correctly serialised

---

.gitignore
README.rst
dataclasses_jsonschema/__init__.py
tests/conftest.py
tests/test_all.py

Close #27 - Deprecate json_schema method on base class & add all_json_schemas
Close #12 - Improve type annotations on from_dict method
Raise custom ValidationError instead of the validation lib ValidationError
Close #13

Add support for type union fields

---

dataclasses_jsonschema/__init__.py
tests/conftest.py

Support dataclasses with non-init fields

---

dataclasses_jsonschema/__init__.py

Improve type annotations to prevent further regressions
Fixes #36
Fixes #38
Fixes #39

Fix regression due to assignment to uninitialised dict

---

dataclasses_jsonschema/__init__.py
tests/conftest.py
tests/test_all.py

Support property descriptions using field metadata

---

dataclasses_jsonschema/__init__.py
tests/test_all.py

Support the `readOnly` and `writeOnly` OpenAPI keywords

---

dataclasses_jsonschema/__init__.py
dataclasses_jsonschema/field_types.py
dataclasses_jsonschema/type_defs.py
tests/test_all.py

Implement field types for ip addresses, uuids and decimals

---

dataclasses_jsonschema/__init__.py
setup.py
tests/test_all.py

* Add typed dict for defining field metadata
* Support swagger extension keywords
Refs #50

Support 'title' and 'examples' keywords

---

dataclasses_jsonschema/__init__.py
tests/test_all.py

Implement `from_object` method

---

dataclasses_jsonschema/__init__.py
setup.py
tests/conftest.py
tests/test_all.py

Replace pyvalico with fastjsonschema

---

dataclasses_jsonschema/__init__.py
tests/test_all.py

Fix warnings emitted as false positives

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Support dataclass inheritance with 'allOf'

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Fix optional type detection with optional union types

---

dataclasses_jsonschema/__init__.py
dataclasses_jsonschema/type_defs.py

Correctly handle NULL values in `to_dict`
Fixes #79

Fix mypy type errors when using the Nullable type

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Add return type annotation for `from_object`
Fixes #84

Improve enum handling in `from_object`

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Support fields prefixed with a single underscore

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Improve handling of None in `from_object`

---

dataclasses_jsonschema/apispec.py
test_issue.py
tests/test_apispec_plugin.py

Fix DuplicateNameError when adding multiple classes

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Add support for OpenAPI 3 discriminators

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Add to_json and from_json convenience methods

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Implement set support

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Now generate an empty schema for the `Any` type

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Add class argument to allow/disallow additional properties

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Add support for python property serialisation

---

setup.py
tox.ini

Pin fastjsonschema version due to custom format errors

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Add `validate_enums` parameter to enable/disable enum checking

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Fix conditional ordering to handle newtype fields correctly

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

discriminator added to schema properties

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Handle unrecognized values for optional enum fields

---

setup.py
tox.ini

Add python 3.9 to tox and classifier.

---

dataclasses_jsonschema/__init__.py

Fix error 
```
File "/opt/pypy/site-packages/dataclasses_jsonschema/__init__.py", line 5, in <module>
from _decimal import Decimal
```
Fixes #149

fix import error in PyPy 7.3.3

---

dataclasses_jsonschema/__init__.py

This is a suggested fix for #147.
I'm not familiar with the code, but it looks reasonable and does fix the test case.
Fixes #147

Fix missing definitions in Optional[Union]

---

.github/workflows/ci.yml
.travis.yml
README.rst
tox.ini

Add gh actions config

---

dataclasses_jsonschema/__init__.py
tests/test_apispec_plugin.py
tests/test_core.py

Add `x-module-name` extension to generated schema

---

dataclasses_jsonschema/__init__.py
dataclasses_jsonschema/field_types.py
dataclasses_jsonschema/type_defs.py
dataclasses_jsonschema/type_hints.py
setup.py
tests/test_peps.py
tox.ini

* Unpin fastjsonschema
* Remove mypy_extensions
Fixes #153
Fixes #152

Add support for PEP585 & PEP604 type defs

---

dataclasses_jsonschema/__init__.py
dataclasses_jsonschema/type_defs.py
setup.py
tests/test_core.py
tests/test_peps.py
tox.ini

Fix handling of untyped container types in Python 3.9

---

dataclasses_jsonschema/__init__.py
tests/test_core.py
tests/test_peps.py

Support overlapping Union types with `anyOf`
Fixes #170

Support using discriminator to determine the Union variant

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Generated tuple schema is now compliant with openapi 3.0

---

dataclasses_jsonschema/__init__.py
tests/test_core.py

Use `issubclass_safe` in type union handling

---

.github/workflows/ci.yml
README.rst
dataclasses_jsonschema/__init__.py
dataclasses_jsonschema/field_types.py
dataclasses_jsonschema/type_defs.py
setup.py
tests/conftest.py
tests/test_core.py
tox.ini

Performance improvements - mainly through optional native libraries for field encoding dates and uuids. Python 3.10 support.

Performance improvements
